name: Testing checkers

on:
    push:
        branches: [ "main" ]
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [ "main" ]

jobs:
  build:
    runs-on:  ubuntu-24.04
    
    strategy:
        matrix:
            buildType: [
                Debug,
                RelWithDebInfo,
            ]

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM
      run: sudo apt update && sudo apt upgrade -y
        sudo add-apt-repository multiverse
        sudo add-apt-repository main
        sudo add-apt-repository universe
        sudo add-apt-repository restricted
        sudo apt-get install --assume-yes \
            clang-15 \
            clang-tidy-15 \
            llvm-15 \
            llvm-15-dev \
            cmake 

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.buildType}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.buildType}}